#!/usr/bin/python
"""
Simple timestamp to date converter. 

Parses second and milisecond precision timestamps
"""
from datetime import datetime
import sys

datetime_format = '%d.%m.%Y %H:%M:%S'

timestamp = sys.argv[1]
if len(timestamp) == 13:
    timestamp = timestamp[:10] 

try:
    datetime_string = datetime.fromtimestamp(int(timestamp)).strftime(datetime_format)
except IndexError:
    print("No argument given")
    sys.exit(1)

print(datetime_string)

